### PR TITLE
Fix #16.

### LINKED ISSUE #16: Assertion failure in grpc call.
[Steps to reproduce]
Build `Dockerfile` using the steps found in [Docker.README.md](https://github.com/GoogleCloudPlatform/cpp-docs-samples/blob/master/speech/api/Docker.README.md). 

run: `./streaming_transcribe_singlethread -b 16000 resources/audio.raw` 

[Error]
```
channel_cc.cc:136]        assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)
```

### PR DESCRIPTION
**Pull request by coryan**
The application must wait until Write() completes before
calling WritesDone() and must wait until the creation of the
asynchronous stream completes before making the first Write()
operation.  I believe this behavior changed with more recent
versions if grpc and that is why the program used to work.

### CODE REVIEW

File: speech/api/streaming_transcribe_singlethread.cc [hunk 1]
```diff
@@ -68,6 +68,27 @@ int main(int argc, char** argv) {
   grpc::ClientContext context;
   auto streamer = speech->AsyncStreamingRecognize(
       &context, &cq, &create_stream);
+
+  bool ok;
```
Comment (SurferJeffAtGoogle) [inline speech/api/streaming_transcribe_singlethread.cc]: I'm paranoid.  Would you mind initializing these variables to false and null?

Comment (coryan) [inline speech/api/streaming_transcribe_singlethread.cc]: Done.

**Comment by coryan** [comment]
PTAL.  And thanks for the suggestions.

I did test the code before my changes with gRPC-1.4.1 and indeed it failed, and tested after the changes and it passes.  I have not tested the code with older versions of gRPC, but experienced similar problems with projects at home.
